// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI tool that takes UI code as input and provides feedback on code quality, accessibility issues, potential improvements, and best practices.
 *
 * - analyzeCodeQuality - A function that handles the code analysis process.
 * - AnalyzeCodeQualityInput - The input type for the analyzeCodeQuality function.
 * - AnalyzeCodeQualityOutput - The return type for the analyzeCodeQuality function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeCodeQualityInputSchema = z.object({
  code: z
    .string()
    .describe(
      'The UI code (e.g., HTML, CSS, JavaScript) to be analyzed for quality and improvements.'
    ),
});
export type AnalyzeCodeQualityInput = z.infer<typeof AnalyzeCodeQualityInputSchema>;

const AnalyzeCodeQualityOutputSchema = z.object({
  feedback: z.string().describe('AI-powered feedback on the UI code quality, accessibility issues, potential improvements, and best practices.'),
});
export type AnalyzeCodeQualityOutput = z.infer<typeof AnalyzeCodeQualityOutputSchema>;

export async function analyzeCodeQuality(input: AnalyzeCodeQualityInput): Promise<AnalyzeCodeQualityOutput> {
  return analyzeCodeQualityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeCodeQualityPrompt',
  input: {schema: AnalyzeCodeQualityInputSchema},
  output: {schema: AnalyzeCodeQualityOutputSchema},
  prompt: `You are an AI code quality analyzer. Review the following UI code and provide feedback on code quality, accessibility issues, potential improvements, and best practices.

UI Code:
{{code}}

Provide detailed feedback, including specific suggestions for improvements. Focus on identifying potential issues and offering actionable advice to enhance the code's robustness and maintainability.`,
});

const analyzeCodeQualityFlow = ai.defineFlow(
  {
    name: 'analyzeCodeQualityFlow',
    inputSchema: AnalyzeCodeQualityInputSchema,
    outputSchema: AnalyzeCodeQualityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
